# Generated by Django 3.1.2 on 2020-10-16 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, default='')),
                ('alimentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alimentos.alimentos')),
            ],
        ),
    ]
